config:
  selfUrl: https://microservices-st-saas
  corsOrigins: https://microservices-st-gateway-web,https://microservices-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://microservices-st-authserver
    requireHttpsMetadata: # "false"
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: microservices-st-saas
  tlsSecret: microservices-tls

image:
  repository: veek/microservices-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      