config:
  selfUrl: # 
  gatewayUrl: # 
  authServer:
    authority: # http://microservices-st-authserver
    requireHttpsMetadata: #"false"
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: # microservices-st-publicweb
  tlsSecret: microservices-tls

image:
  repository: veek/microservices-app-publicweb
  tag: latest
  pullPolicy: IfNotPresent

env: {}