# auth-server sub-chart override
authserver:
  config:
    selfUrl: https://microservices-st-authserver    
    corsOrigins: https://microservices-st-gateway-web,https://microservices-st-gateway-web-public
    allowedRedirectUrls: https://microservices-st-angular
    identityService:
      connString: "Server=microservices-st-sqldb,1433;Database=MicroService_Identity;User Id=sa;password=myPassw@rd"
    administrationService:
      connString: "Server=microservices-st-sqldb,1433;Database=MicroService_Administration;User Id=sa;password=myPassw@rd"
    saasService:
      connString: "Server=microservices-st-sqldb,1433;Database=MicroService_Saas;User Id=sa;password=myPassw@rd"
    authServer:
      authority: http://microservices-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: microservices-st-redis
    rabbitmqHost: microservices-st-rabbitmq
    elasticsearchUrl: http://microservices-st-elasticsearch
  ingress:
    host: microservices-st-authserver
  image:
    repository: veek/microservices-app-authserver
    tag: latest

# identity-service sub-chart override
identity:
  config:
    selfUrl: https://microservices-st-identity
    corsOrigins: https://microservices-st-gateway-web,https://microservices-st-gateway-web-public
    connectionStrings:
      identityService: "Server=microservices-st-sqldb,1433;Database=MicroService_Identity;User Id=sa;password=myPassw@rd"
      administrationService: "Server=microservices-st-sqldb,1433;Database=MicroService_Administration;User Id=sa;password=myPassw@rd"
      saasService: "Server=microservices-st-sqldb,1433;Database=MicroService_Saas;User Id=sa;password=myPassw@rd"
    authServer:
      authority: http://microservices-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: microservices-st-redis
    rabbitmqHost: microservices-st-rabbitmq
    elasticsearchUrl: http://microservices-st-elasticsearch
  identityServerClients: # Seeded Clients
    angularRootUrl: https://microservices-st-angular/
    webRootUrl: https://microservices-st-web/
    blazorRootUrl: https://microservices-st-blazor/
    blazorServerRootUrl: https://microservices-st-blazor-server/
    publicWebRootUrl: https://microservices-st-public-web/
    webGatewayRootUrl: https://microservices-st-gateway-web/
    publicWebGatewayRootUrl: https://microservices-st-gateway-web-public/ 
  ingress:
    host: microservices-st-identity
  image:
    repository: veek/microservices-service-identity
    tag: latest

# administration-service sub-chart override
administration:
  config:
    selfUrl: https://microservices-st-administration
    gatewayUrl: https://microservices-st-gateway-internal/
    corsOrigins: https://microservices-st-gateway-web,https://microservices-st-gateway-web-public
    connectionStrings:
      administrationService: "Server=microservices-st-sqldb,1433;Database=MicroService_Administration;User Id=sa;password=myPassw@rd"
      saasService: "Server=microservices-st-sqldb,1433;Database=MicroService_Saas;User Id=sa;password=myPassw@rd"    
    authServer:
      authority: http://eshop-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: microservices-st-redis
    rabbitmqHost: microservices-st-rabbitmq
    elasticsearchUrl: http://microservices-st-elasticsearch
  synchedCommunication: # Used for server-to-server (client-credentials) communication with identityService for user permissions
    authority: https://microservices-st-authserver
  ingress:
    host: microservices-st-administration
  image:
    repository: veek/microservices-service-administration
    tag: latest

# saas-service sub-chart override
saas:
  config:
    selfUrl: https://microservices-st-saas
    corsOrigins: https://microservices-st-gateway-web,https://microservices-st-gateway-web-public
    connectionStrings:
      administrationService: "Server=microservices-st-sqldb,1433;Database=MicroService_Administration;User Id=sa;password=myPassw@rd"
      saasService: "Server=microservices-st-sqldb,1433;Database=MicroService_Saas;User Id=sa;password=myPassw@rd"
    authServer:
      authority: http://microservices-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: microservices-st-redis
    rabbitmqHost: microservices-st-rabbitmq
    elasticsearchUrl: http://microservices-st-elasticsearch
  ingress:
    host: microservices-st-saas
  image:
    repository: veek/microservices-service-administration
    tag: latest  

# product-service sub-chart override
product:
  config:
    selfUrl: https://microservices-st-product
    corsOrigins: https://microservices-st-gateway-web,https://microservices-st-gateway-web-public
    connectionStrings:
      productService: "Server=microservices-st-sqldb,1433;Database=MicroService_ProductService;User Id=sa;password=myPassw@rd"
      administrationService: "Server=microservices-st-sqldb,1433;Database=MicroService_Administration;User Id=sa;password=myPassw@rd"
      saasService: "Server=microservices-st-sqldb,1433;Database=MicroService_Saas;User Id=sa;password=myPassw@rd"
    authServer:
      authority: http://microservices-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: microservices-st-redis
    rabbitmqHost: microservices-st-rabbitmq
    elasticsearchUrl: http://microservices-st-elasticsearch
  ingress:
    host: microservices-st-product    
  image:
    repository: veek/microservices-service-product
    tag: latest

# gateway-web sub-chart override
gateway-web:
  config:
    selfUrl: https://microservices-st-gateway-web
    corsOrigins: https://microservices-st-angular
    globalConfigurationBaseUrl: http://microservices-st-gateway-web
    authServer:
      authority: http://microservices-st-authserver
      requireHttpsMetadata: "false"  
    dotnetEnv: Staging
    redisHost: microservices-st-redis
    rabbitmqHost: microservices-st-rabbitmq
    elasticsearchUrl: http://microservices-st-elasticsearch
  reRoutes:
    authserver:
      schema: http
      host: microservices-st-authserver
      port: 80
    identityService:
      schema: # http
      host: microservices-st-identity
      port: 80
    administrationService:
      schema: http
      host: microservices-st-administration
      port: 80
    saasService:
      schema: # http
      host: microservices-st-saas
      port: 80
    productService:
      schema: http
      host: microservices-st-saas
      port: 80  
  ingress:
    host: microservices-st-gateway-web
  image:
    repository: veek/microservices-gateway-web
    tag: latest
    pullPolicy: IfNotPresent

# gateway-web-public sub-chart override
gateway-web-public:
  config:
    selfUrl: https://microservices-st-gateway-web-public
    globalConfigurationBaseUrl: http://microservices-st-gateway-web-public
    corsOrigins: https://microservices-st-gateway-web,https://microservices-st-gateway-web-public
    authServer:
      authority: http://microservices-st-authserver
      requireHttpsMetadata: "false"  
    dotnetEnv: Staging 
    redisHost: microservices-st-redis
    rabbitmqHost: microservices-st-rabbitmq
    elasticsearchUrl: http://microservices-st-elasticsearch
  reRoutes:
    identityService:
      schema: http
      host: microservices-st-identity
      port: 80
    administrationService:
      schema: http
      host: microservices-st-administration
      port: 80
    productService:
      schema: http
      host: microservices-st-product
      port: 80  
  ingress:
    host: microservices-st-gateway-web-public
    tlsSecret: microservices-tls
  image:
    repository: veek/microservices-gateway-web-public
    tag: latest
    pullPolicy: IfNotPresent

kibana:
  config:
    elasticsearchUrl: http://microservices-st-elasticsearch:9200

# dbmigrator sub-chart override
dbmigrator:
  config:
    connectionStrings:
      identityService: "Server=microservices-st-sqldb,1433;Database=MicroService_Identity;User Id=sa;password=myPassw@rd"
      administrationService: "Server=microservices-st-sqldb,1433;Database=MicroService_Administration;User Id=sa;password=myPassw@rd"
      saasService: "Server=microservices-st-sqldb,1433;Database=MicroService_Saas;User Id=sa;password=myPassw@rd"
      productService: "Server=microservices-st-sqldb,1433;Database=MicroService_ProductService;User Id=sa;password=myPassw@rd"
    dotnetEnv: Staging  
  identityServerClients: # Seeded Clients
    angularRootUrl: https://microservices-st-angular/
    webRootUrl: https://microservices-st-web/
    blazorRootUrl: https://microservices-st-blazor/
    blazorServerRootUrl: https://microservices-st-blazor-server/
    publicWebRootUrl: https://microservices-st-public-web/
    webGatewayRootUrl: https://microservices-st-gateway-web/
    publicWebGatewayRootUrl: https://microservices-st-gateway-web-public/ 
  image:
    repository: veek/microservices-db-migrator
    tag: latest
    pullPolicy: IfNotPresent  

# Public Web application sub-chart override
publicweb:
  config:
    selfUrl: https://microservices-st-publicweb
    gatewayUrl: https://microservices-st-gateway-web-public
    authServer:
      authority: http://microservices-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging 
    redisHost: microservices-st-redis
    rabbitmqHost: microservices-st-rabbitmq
    elasticsearchUrl: http://microservices-st-elasticsearch
  ingress:
    host: microservices-st-publicweb
    tlsSecret: microservices-tls
  image:
    repository: veek/microservices-app-publicweb
    tag: latest
    pullPolicy: IfNotPresent

# Web(MVC) backoffice application sub-chart override
web:
  config:
    selfUrl: https://microservices-st-web
    gatewayUrl: https://microservices-st-gateway-web
    authServer:
      authority: http://microservices-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging 
    redisHost: microservices-st-redis
    rabbitmqHost: microservices-st-rabbitmq
    elasticsearchUrl: http://microservices-st-elasticsearch
  ingress:
    host: microservices-st-web
    tlsSecret: microservices-tls
  image:
    repository: veek/microservices-app-web
    tag: latest
    pullPolicy: IfNotPresent

# Angular backoffice application sub-chart override
angular:
  config:
    selfUrl: https://microservices-st-angular
    gatewayUrl: https://microservices-st-gateway-web
    authServer:
      authority: http://microservices-st-authserver
      requireHttpsMetadata: "false"
  ingress:
    host: microservices-st-angular
    tlsSecret: microservices-tls
  image:
    repository: veek/microservices-app-angular
    tag: latest
    pullPolicy: IfNotPresent

# Default values for Microservices.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
